add env

diff --git a/.github/workflows/master_khrental.yml b/.github/workflows/master_khrental.yml
--- a/.github/workflows/master_khrental.yml
+++ b/.github/workflows/master_khrental.yml
@@ -70,6 +70,7 @@ jobs:
           # Create startup script
           cat << 'EOF' > startup.sh
           #!/bin/bash
+          set -e  # Exit immediately if a command exits with a non-zero status
           cd /home/site/wwwroot
           npm install -g serve
           serve -s . -p 8080
@@ -137,13 +138,16 @@ jobs:
           echo "Ensuring startup script is executable:"
           chmod +x startup.sh
 
-          - name: Login to Azure
-          uses: azure/login@v2
-          with:
-            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EEDC2329EBDE4906AAD5DBEFBDBD8982 }}
-            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B76BB5BB72494662B2E55987D0F9FEC7 }}
-            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62093CB513E141DEBC62ACAB8F0862DB }}
-            
+      - name: Debug startup script
+        run: bash -x startup.sh
+
+      - name: Login to Azure
+        uses: azure/login@v2
+        with:
+          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EEDC2329EBDE4906AAD5DBEFBDBD8982 }}
+          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B76BB5BB72494662B2E55987D0F9FEC7 }}
+          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62093CB513E141DEBC62ACAB8F0862DB }}
+
       - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v2
         with:
